version: '3'

services:
  srvc1:
    build: 
      context: ./srvc1
    expose:
      - "8199"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 3
    networks:
      - app-network
    stop_grace_period: 20s  

  srvc2:
    build: 
      context: ./srvc2
    expose:
      - "8199"
    networks:
      - app-network
    stop_grace_period: 20s  


  nginx:
    image: nginx:latest
    ports:
      - "8198:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - srvc1
      - srvc2
    networks:
      - app-network
    stop_grace_period: 20s  

    
networks:
  app-network:
    driver: bridge